/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/_layout'
import { Route as ShopIndexRouteImport } from './routes/_shop/index'
import { Route as ShopCartRouteImport } from './routes/_shop/cart'
import { Route as ShopSRouteImport } from './routes/_shop/s'
import { Route as ProtectedLayoutAccountRouteImport } from './routes/_protected/_layout/account'
import { Route as ProtectedLayoutCheckoutRouteImport } from './routes/_protected/_layout/checkout'
import { Route as ProtectedLayoutOrdersRouteImport } from './routes/_protected/_layout/orders'
import { Route as ShopPSlugRouteImport } from './routes/_shop/p.$slug'
import { Route as ShopStoreSlugRouteImport } from './routes/_shop/store.$slug'
import { Route as ProtectedLayoutSellIndexRouteImport } from './routes/_protected/_layout/sell.index'
import { Route as ProtectedLayoutSellStoreIdIndexRouteImport } from './routes/_protected/_layout/sell.$storeId.index'
import { Route as ProtectedLayoutSellStoreIdNewRouteImport } from './routes/_protected/_layout/sell.$storeId.new'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ProtectedRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSRoute = ShopSRouteImport.update({
  id: '/s',
  path: '/s',
  getParentRoute: () => ShopRoute,
} as any)
const ProtectedLayoutAccountRoute = ProtectedLayoutAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutCheckoutRoute = ProtectedLayoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutOrdersRoute = ProtectedLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ShopPSlugRoute = ShopPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopStoreSlugRoute = ShopStoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ProtectedLayoutSellIndexRoute =
  ProtectedLayoutSellIndexRouteImport.update({
    id: '/sell/',
    path: '/sell/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutSellStoreIdIndexRoute =
  ProtectedLayoutSellStoreIdIndexRouteImport.update({
    id: '/sell/$storeId/',
    path: '/sell/$storeId/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutSellStoreIdNewRoute =
  ProtectedLayoutSellStoreIdNewRouteImport.update({
    id: '/sell/$storeId/new',
    path: '/sell/$storeId/new',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/cart': typeof ShopCartRoute
  '/s': typeof ShopSRoute
  '/account': typeof ProtectedLayoutAccountRoute
  '/checkout': typeof ProtectedLayoutCheckoutRoute
  '/orders': typeof ProtectedLayoutOrdersRoute
  '/p/$slug': typeof ShopPSlugRoute
  '/store/$slug': typeof ShopStoreSlugRoute
  '/sell/': typeof ProtectedLayoutSellIndexRoute
  '/sell/$storeId/new': typeof ProtectedLayoutSellStoreIdNewRoute
  '/sell/$storeId/': typeof ProtectedLayoutSellStoreIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShopIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/cart': typeof ShopCartRoute
  '/s': typeof ShopSRoute
  '/account': typeof ProtectedLayoutAccountRoute
  '/checkout': typeof ProtectedLayoutCheckoutRoute
  '/orders': typeof ProtectedLayoutOrdersRoute
  '/p/$slug': typeof ShopPSlugRoute
  '/store/$slug': typeof ShopStoreSlugRoute
  '/sell': typeof ProtectedLayoutSellIndexRoute
  '/sell/$storeId/new': typeof ProtectedLayoutSellStoreIdNewRoute
  '/sell/$storeId': typeof ProtectedLayoutSellStoreIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_shop': typeof ShopRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_protected/_layout': typeof ProtectedLayoutRouteWithChildren
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/s': typeof ShopSRoute
  '/_shop/': typeof ShopIndexRoute
  '/_protected/_layout/account': typeof ProtectedLayoutAccountRoute
  '/_protected/_layout/checkout': typeof ProtectedLayoutCheckoutRoute
  '/_protected/_layout/orders': typeof ProtectedLayoutOrdersRoute
  '/_shop/p/$slug': typeof ShopPSlugRoute
  '/_shop/store/$slug': typeof ShopStoreSlugRoute
  '/_protected/_layout/sell/': typeof ProtectedLayoutSellIndexRoute
  '/_protected/_layout/sell/$storeId/new': typeof ProtectedLayoutSellStoreIdNewRoute
  '/_protected/_layout/sell/$storeId/': typeof ProtectedLayoutSellStoreIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/cart'
    | '/s'
    | '/account'
    | '/checkout'
    | '/orders'
    | '/p/$slug'
    | '/store/$slug'
    | '/sell/'
    | '/sell/$storeId/new'
    | '/sell/$storeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/cart'
    | '/s'
    | '/account'
    | '/checkout'
    | '/orders'
    | '/p/$slug'
    | '/store/$slug'
    | '/sell'
    | '/sell/$storeId/new'
    | '/sell/$storeId'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_shop'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/_layout'
    | '/_shop/cart'
    | '/_shop/s'
    | '/_shop/'
    | '/_protected/_layout/account'
    | '/_protected/_layout/checkout'
    | '/_protected/_layout/orders'
    | '/_shop/p/$slug'
    | '/_shop/store/$slug'
    | '/_protected/_layout/sell/'
    | '/_protected/_layout/sell/$storeId/new'
    | '/_protected/_layout/sell/$storeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/_layout': {
      id: '/_protected/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/s': {
      id: '/_shop/s'
      path: '/s'
      fullPath: '/s'
      preLoaderRoute: typeof ShopSRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_protected/_layout/account': {
      id: '/_protected/_layout/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedLayoutAccountRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/checkout': {
      id: '/_protected/_layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ProtectedLayoutCheckoutRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/orders': {
      id: '/_protected/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ProtectedLayoutOrdersRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_shop/p/$slug': {
      id: '/_shop/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof ShopPSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/store/$slug': {
      id: '/_shop/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof ShopStoreSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_protected/_layout/sell/': {
      id: '/_protected/_layout/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof ProtectedLayoutSellIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/sell/$storeId/': {
      id: '/_protected/_layout/sell/$storeId/'
      path: '/sell/$storeId'
      fullPath: '/sell/$storeId/'
      preLoaderRoute: typeof ProtectedLayoutSellStoreIdIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/sell/$storeId/new': {
      id: '/_protected/_layout/sell/$storeId/new'
      path: '/sell/$storeId/new'
      fullPath: '/sell/$storeId/new'
      preLoaderRoute: typeof ProtectedLayoutSellStoreIdNewRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutAccountRoute: typeof ProtectedLayoutAccountRoute
  ProtectedLayoutCheckoutRoute: typeof ProtectedLayoutCheckoutRoute
  ProtectedLayoutOrdersRoute: typeof ProtectedLayoutOrdersRoute
  ProtectedLayoutSellIndexRoute: typeof ProtectedLayoutSellIndexRoute
  ProtectedLayoutSellStoreIdNewRoute: typeof ProtectedLayoutSellStoreIdNewRoute
  ProtectedLayoutSellStoreIdIndexRoute: typeof ProtectedLayoutSellStoreIdIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutAccountRoute: ProtectedLayoutAccountRoute,
  ProtectedLayoutCheckoutRoute: ProtectedLayoutCheckoutRoute,
  ProtectedLayoutOrdersRoute: ProtectedLayoutOrdersRoute,
  ProtectedLayoutSellIndexRoute: ProtectedLayoutSellIndexRoute,
  ProtectedLayoutSellStoreIdNewRoute: ProtectedLayoutSellStoreIdNewRoute,
  ProtectedLayoutSellStoreIdIndexRoute: ProtectedLayoutSellStoreIdIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ShopRouteChildren {
  ShopCartRoute: typeof ShopCartRoute
  ShopSRoute: typeof ShopSRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopPSlugRoute: typeof ShopPSlugRoute
  ShopStoreSlugRoute: typeof ShopStoreSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCartRoute: ShopCartRoute,
  ShopSRoute: ShopSRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopPSlugRoute: ShopPSlugRoute,
  ShopStoreSlugRoute: ShopStoreSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
